services:
  application:
    container_name: hanzi-client
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./nginx/${ENVIRONMENT}:/etc/nginx/conf.d
    networks:
      - fraore-network
networks:
  fraore-network:
    external: true